language: node_js
node_js:
  - "6"

notifications:
  email:
    on_failure: always
    on_success: never

script:
  - cd backend && npm install && npm run lint && npm test
  - cd ../frontend && npm install --save-dev && npm run lint
